#!/bin/bash
apt update
apt install screen figlet toilet cowsay -y 

figlet -c Artistas da Monitoracao

cd /tmp 
rm *deb* 
alias apt-get='apt-get -y' 
#VERSION='5.2.18' && \
apt-get install -y linux-headers-generic build-essential dkms  # && \
#sudo wget "http://download.virtualbox.org/virtualbox/$VERSION/VBoxGuestAdditions_$VERSION.iso" && \
#sudo mkdir /media/VBoxGuestAdditions && \
#sudo mount -o loop,ro "VBoxGuestAdditions_$VERSION.iso" /media/VBoxGuestAdditions && \
#sudo sh /media/VBoxGuestAdditions/VBoxLinuxAdditions.run && \
#sudo umount /media/VBoxGuestAdditions && \
#sudo rm -rf "VBoxGuestAdditions_$VERSION.iso" && \
#sudo rmdir /media/VBoxGuestAdditions

rm /tmp/finish

#wget https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+bionic_all.deb
wget https://repo.zabbix.com/zabbix/4.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.4-1+bionic_all.deb -O zabbix-4.4.1.deb
#dpkg -i zabbix-release_4.0-2+bionic_all.deb
dpkg -i zabbix-4.4.1.deb 
apt update 
apt install build-essential module-assistant 
apt install locales  
locale-gen pt_BR.UTF-8 
m-a prepare 
# dpkg-reconfigure locales
update-locale LANG=pt_BR.UTF-8 
apt install zabbix-server-mysql zabbix-frontend-php zabbix-agent -y
apt install apache2 -y
apt install php php-cgi libapache2-mod-php php-common php-pear php-mbstring -y
apt install mariadb-server -y
apt install zabbix-server-mysql zabbix-agent zabbix-frontend-php php-mysql php-gd php-xml-util php-bcmath php-net-socket php-gettext -y
apt install nmap -y 
apt install snmp -y  
apt install snmp-mibs-downloader -y 
apt install zabbix-apache-conf -y 
apt install jq -y

export DEBIAN_FRONTEND=noninteractive

mysql -uroot -e "CREATE DATABASE zabbix CHARACTER SET utf8 COLLATE utf8_bin"; 
mysql -uroot -e "CREATE USER 'zabbix'@'localhost'";
mysql -uroot -e "GRANT ALL ON zabbix.* TO 'zabbix'@'localhost'";

mysql -uroot -e "SHOW DATABASES";
mysql -uroot -e "SELECT host, user FROM mysql.user";
mysql -uroot -e "SHOW GRANTS FOR 'zabbix'@'localhost'";

zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -uroot zabbix

a2enconf zabbix-frontend-php 
> /var/www/html/index.html 

sed -i 's/# php_value date.timezone Europe\/Riga/php_value date.timezone America\/Sao_Paulo/g' /etc/apache2/conf-enabled/zabbix.conf
systemctl restart apache2 

sudo apt-get install -y adduser libfontconfig1
wget https://dl.grafana.com/oss/release/grafana_7.3.7_amd64.deb
sudo dpkg -i grafana_7.3.7_amd64.deb

grafana-cli plugins install alexanderzobnin-zabbix-app
grafana-cli plugins update alexanderzobnin-zabbix-app
systemctl restart grafana-server 
service mysql restart 
service zabbix-server restart 
service zabbix-agent restart 
iptables -A INPUT -p tcp -s localhost --dport 3306 -j ACCEPT 
iptables -A INPUT -p tcp --dport 3306 -j DROP 
touch /tmp/finish 


iptables-save | grep 3306
systemctl status mysql | grep Active
systemctl status zabbix-server | grep Active
systemctl status zabbix-agent | grep Active
systemctl status grafana-server | grep Active
cd /usr/share/snmp/mibs
git clone https://github.com/arturbrasil/vendors.git
clear

cd /tmp
wget https://raw.githubusercontent.com/arturbrasil/curriculo/gh-pages/zabbix-datasource

for i in /tmp/zabbix-datasource ; do \
    curl -X "POST" "http://127.0.0.1:3000/api/datasources" \
    -H "Content-Type: application/json" \
    --user Admin:zabbix \
    --data-binary @$i
done

grafana_host="http://localhost:3000"
grafana_cred="admin:admin"
grafana_datasource="zabbix"
wget https://raw.githubusercontent.com/arturbrasil/curriculo/gh-pages/dash-redes-sociais.json

cat dash-redes-sociais.json | jq '. * {overwrite: true, dashboard: {id: null}}' | curl -s -k -u "$grafana_cred" -XPOST -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    $grafana_host/api/dashboards/import  -d  @- ;

figlet -c FINALIZADO!
cowsay -f tux "Acesse o IP/zabbix do servidor no seu navegador para visualizar o zabbix!      Usuário: Admin - Senha: zabbix  !"
cowsay -f tux "Acesse o IP:3000 do servidor no seu navegador para visualizar o grafana!       Usuário: admin - Senha: admin   !"

#wget https://bit.ly/2SY7SBv -O check.sh && bash $_
#sudo apt-get install virtualbox-guest-additions-iso

#sh /media/cdrom/VBoxLinuxAdditions.run

cd /usr/share/snmp/mibs
git clone https://github.com/arturbrasil/vendors.git
apt-get install snmpd
mkdir -p $HOME/.snmp
for i in `ls -d /usr/share/snmp/mibs/vendors/*/`; do
 echo "mibdirs +$i" > $HOME/.snmp/snmp.conf
 export MIBDIRS=$MIBDIRS:$i
done

export MIBS=+ALL
