#!/bin/bash
apt install screen figlet toilet -y
figlet -c Artistas da Monitoração
wget -q https://raw.githubusercontent.com/arturbrasil/curriculo/gh-pages/zabbix4 -O /tmp/zabbix4
chmod +x /tmp/zabbix4
screen -d -m -S ZABBIX /tmp/zabbix4
