#!/bin/bash

# Atualizar repositórios de pacotes
apt-get -qq update

# Instalar dependências
sudo apt-get -qq -y install gnupg2 wget sudo

# Instalação do PostgreSQL 14
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt-get -qq update
sudo apt-get -qq -y install postgresql-14

# Iniciar PostgreSQL 14
sudo systemctl enable --now postgresql@14-main

# Instalação do TimescaleDB 2.1.1
sudo sh -c 'echo "deb https://packagecloud.io/timescale/timescaledb/debian/ buster main" > /etc/apt/sources.list.d/timescaledb.list'
wget --quiet -O - https://packagecloud.io/timescale/timescaledb/gpgkey | sudo apt-key add -
sudo apt-get -qq update
sudo apt-get -qq -y install timescaledb-postgresql-14=2.1.1

# Iniciar o TimescaleDB
sudo systemctl enable --now postgresql@14-main

# Instalar Zabbix Server, frontend e outras dependências
sudo apt-get -qq update
sudo apt-get -qq -y install zabbix-server-pgsql zabbix-frontend-php php7.4-pgsql zabbix-nginx-conf zabbix-agent

# Configurar PostgreSQL para Zabbix
zcat /usr/share/doc/zabbix-server-pgsql*/create.sql.gz | sudo -u postgres psql zabbix

# Configurar Zabbix Server
sudo sed -i "s/# DBHost=localhost/DBHost=localhost/" /etc/zabbix/zabbix_server.conf
sudo sed -i "s/# DBPassword=/DBPassword=monflix/" /etc/zabbix/zabbix_server.conf

# Configurar Zabbix frontend
sudo tee /etc/zabbix/web/zabbix.conf.php <<EOL
<?php
    \$DB["TYPE"] = "POSTGRESQL";
    \$DB["SERVER"] = "localhost";
    \$DB["PORT"] = "5432";
    \$DB["DATABASE"] = "zabbix";
    \$DB["USER"] = "zabbix";
    \$DB["PASSWORD"] = "monflix";
    \$DB["SCHEMA"] = "";
    \$ZBX_SERVER = "localhost";
    \$ZBX_SERVER_PORT = "10051";
    \$ZBX_SERVER_NAME = "zabbix";
    \$IMAGE_FORMAT_DEFAULT = IMAGE_FORMAT_PNG;
EOL

# Configurar o fuso horário do PHP
sudo sed -i "s/php_value\[date.timezone\] = .*/php_value\[date.timezone\] = America\/Sao_Paulo/" /etc/zabbix/php-fpm.conf

# Configurar Nginx para Zabbix
sudo sed -i "s/#        listen          80;/        listen 80 default_server;\\n        listen [::]:80 default_server;/" /etc/zabbix/nginx.conf
sudo sed -i "s/#        server_name     example.com;/        server_name _;/" /etc/zabbix/nginx.conf
sudo rm /etc/nginx/sites-available/default
sudo rm /etc/nginx/sites-enabled/default
sudo rm /etc/nginx/conf.d/zabbix.conf
sudo ln -s /etc/zabbix/nginx.conf /etc/nginx/sites-available/default
sudo ln -s /etc/zabbix/nginx.conf /etc/nginx/sites-enabled/default

# Reiniciar os serviços
sudo systemctl restart postgresql@14-main
sudo systemctl restart zabbix-server
sudo systemctl restart php7.4-fpm
sudo systemctl restart nginx
