#!/bin/bash

# Atualizar repositórios de pacotes
sudo apt-get -qq update

# Instalar dependências
sudo apt-get -qq -y install gnupg2 wget sudo php-pgsql snmpd

# Instalação do PostgreSQL 14
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt-get -qq update
sudo apt-get -qq -y install postgresql-14

# Iniciar PostgreSQL 14
sudo systemctl enable --now postgresql@14-main

# Instalação do TimescaleDB 2.1.1 para PostgreSQL 14
sudo sh -c 'echo "deb https://packagecloud.io/timescale/timescaledb/debian/ $(lsb_release -cs) main" > /etc/apt/sources.list.d/timescaledb.list'
wget --quiet -O - https://packagecloud.io/timescale/timescaledb/gpgkey | sudo apt-key add -
sudo apt-get -qq update
sudo apt-get -qq -y install timescaledb-2-postgresql-14

# Iniciar o TimescaleDB
sudo systemctl enable --now postgresql@14-main

# Configurar SNMPD para aceitar a comunidade "monflix" para todos os OIDs 1.3
echo "com2sec readonly  default         monflix" | sudo tee -a /etc/snmp/snmpd.conf
echo "group MyROGroup v1         readonly" | sudo tee -a /etc/snmp/snmpd.conf
echo "view all    included  .1.3       80" | sudo tee -a /etc/snmp/snmpd.conf
echo "access MyROGroup \"\"      any       noauth    0      all    none   none" | sudo tee -a /etc/snmp/snmpd.conf

# Reiniciar SNMPD
sudo systemctl restart snmpd

# Instalar Nginx
sudo apt-get -qq -y install nginx

# Configurar Nginx para Zabbix
sudo tee /etc/nginx/sites-available/zabbix <<EOL
server {
    listen 80;
    server_name your_domain_or_IP;

    root /usr/share/zabbix;

    access_log  /var/log/nginx/zabbix-access.log;
    error_log   /var/log/nginx/zabbix-error.log;

    location / {
        index index.php index.html index.htm;
        try_files \$uri \$uri/ /index.php?\$args;
    }

    location ~ \.php$ {
        fastcgi_pass unix
